### ISSUE TITLE
Chaotic Feat:Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [vansh-codes/ChaosWeb#214]
### Describe your chaotic idea

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

### Add Screenshots or Sketches

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by vansh-codes** [comment]
You will be doing this for the React website right? 
React website is in `chaosweb-v@2` folder/directory

- HTML Website will be removed soon so doing SEO enhancements on it is not needed, thats why you should do it in React folder

I am assigning it to you to do it in React folder, if you are not comfortable in it then feel free to close the issue

**Comment by vansh-codes** [comment]
Completed

**Comment by myselfshivams** [comment]
> Completed

Hi @vansh-codes Please add a level tag; otherwise, GSSoC will not recognize this. If possible, please add a higher-level tag.
