### ISSUE TITLE
Chaotic Feat: Improve Scroll Bar and Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [vansh-codes/ChaosWeb#48]
### Description
The current Scroll bar Ui has a very basic layout and outdated design and site Loading has no preloader. The screen becomes blank when the website loads. Enhancing the colour scheme of Thumb and Track, improving the preloader and modernizing the scroll bar design would greatly improve the user experience and website presentation

### Tasks:

- Redesign the Scroll bar and preloader for better visual appeal.
- Improving the scroll bar thump and track.
- Improving the preloader.

@vansh-codes   can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

### Add Screenshots or Sketches
**Without Preloader and without improvement in Scroll BAR**

https://github.com/user-attachments/assets/3727fb7c-4032-440b-b185-47974024d435

###  Preloader Mockup
https://github.com/user-attachments/assets/eef3abe5-db44-4f17-abd0-292f63a89de9

### Confirm

- [X] I understand that my idea will add to the chaos and I'm okay with it
- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this feature
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor

**Comment by VidhanThakur09** [comment]
How about these

https://github.com/user-attachments/assets/a2b9d568-3bd3-4c3e-a3ef-14315f21cf28


https://github.com/user-attachments/assets/e40df441-061a-457a-86b9-aad69f394d89

**Comment by vansh-codes** [comment]
The first one looks chaotic! you can go with the first one
Also is that your design or you have copied from somewhere?
Its okay even if you have copied I am just curious to know as I am seeing it for the first time

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me, I have taken inspiration from other preloaders creators
.

**Comment by vansh-codes** [comment]
Wow its great!
You gonna create this loader from code right??

**Comment by VidhanThakur09** [comment]
yes

**Comment by vansh-codes** [comment]
It deserves level 3 😉

**Comment by VidhanThakur09** [comment]
thank you for your appreciation, when you migrate to react let me know i will convert the preloader to your code pattern.
